users: list = [
    {'name': 'Żerom', 'posts': 1, 'city': 'Warszawa'},
    {'name': 'Dominik', 'posts': 3, 'city': 'Poznań'},
    {'name': 'Szymon z wąsem', 'posts': 5, 'city': 'Toruń'},
    {'name': 'Szymon', 'posts': 7, 'city': 'Łódź'},
    {'name': 'Patryk', 'posts': 9, 'city': 'Kielce'},
    {'name': 'Dominik', 'posts': 12, 'city': 'Siedlce'},
    {'name': 'Kinga', 'posts': 14, 'city': 'Gdynia'},
    {'name': 'Amelia', 'posts': 2, 'city': 'Bydgoszcz'},
    {'name': 'Karolina', 'posts': 8, 'city': 'Kraków'},
    {'name': 'Julia', 'posts': 4, 'city': 'Zamość'},
    {'name': 'Aleksandra', 'posts': 60, 'city': 'Radom'},
    {'name': 'Patrycja', 'posts': 13, 'city': 'Kraśnik'},
    {'name': 'Patrycja', 'posts': 8, 'city': 'Mińsk Mazowiecki'},
    {'name': 'Patrycja', 'posts': 7, 'city': 'Świętoszów'},
    {'name': 'Michał', 'posts': 4, 'city': 'Kluczbork'},
]